// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

namespace NationalParks.Migrations
{
    [DbContext(typeof(NationalParksContext))]
    [Migration("20201030155622_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualVisitors");

                    b.Property<string>("DateEstablished");

                    b.Property<double>("ParkArea");

                    b.Property<string>("ParkDescription");

                    b.Property<string>("ParkLocation");

                    b.Property<string>("ParkName");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            AnnualVisitors = 4020288,
                            DateEstablished = "March 1, 1872",
                            ParkArea = 2219790.71,
                            ParkDescription = "test",
                            ParkLocation = "Wyoming, Montana, Idaha",
                            ParkName = "YellowStone"
                        },
                        new
                        {
                            ParkId = 2,
                            AnnualVisitors = 1246053,
                            DateEstablished = "September 25, 1890",
                            ParkArea = 404062.63,
                            ParkDescription = "test",
                            ParkLocation = "California",
                            ParkName = "Sequoia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
