// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

namespace NationalParks.Migrations
{
    [DbContext(typeof(NationalParksContext))]
    [Migration("20201030232859_StateParkYearRound")]
    partial class StateParkYearRound
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParks.Models.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualVisitors");

                    b.Property<string>("DateEstablished")
                        .IsRequired();

                    b.Property<double>("NationalParkArea");

                    b.Property<string>("NationalParkDescription")
                        .IsRequired();

                    b.Property<string>("NationalParkLocation")
                        .IsRequired();

                    b.Property<string>("NationalParkName")
                        .IsRequired();

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            NationalParkId = 1,
                            AnnualVisitors = 4020288,
                            DateEstablished = "March 1, 1872",
                            NationalParkArea = 2219790.71,
                            NationalParkDescription = "test",
                            NationalParkLocation = "Wyoming, Montana, Idaha",
                            NationalParkName = "YellowStone"
                        },
                        new
                        {
                            NationalParkId = 2,
                            AnnualVisitors = 1246053,
                            DateEstablished = "September 25, 1890",
                            NationalParkArea = 404062.63,
                            NationalParkDescription = "test",
                            NationalParkLocation = "California",
                            NationalParkName = "Sequoia"
                        },
                        new
                        {
                            NationalParkId = 3,
                            AnnualVisitors = 4422861,
                            DateEstablished = "October 1, 1890",
                            NationalParkArea = 761747.5,
                            NationalParkDescription = "test",
                            NationalParkLocation = "California",
                            NationalParkName = "Yosemite"
                        },
                        new
                        {
                            NationalParkId = 4,
                            AnnualVisitors = 1501621,
                            DateEstablished = "March 2, 1899",
                            NationalParkArea = 236381.64000000001,
                            NationalParkDescription = "test",
                            NationalParkLocation = "Washington",
                            NationalParkName = "Mount Rainier"
                        },
                        new
                        {
                            NationalParkId = 5,
                            AnnualVisitors = 704512,
                            DateEstablished = "May 22, 1902",
                            NationalParkArea = 236381.64000000001,
                            NationalParkDescription = "test",
                            NationalParkLocation = "Oregon Lake",
                            NationalParkName = "Crater Lake"
                        });
                });

            modelBuilder.Entity("NationalParks.Models.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("StateParkDescription")
                        .IsRequired();

                    b.Property<string>("StateParkName")
                        .IsRequired();

                    b.Property<bool>("YearRound");

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            StateParkId = 1,
                            State = "Oregon",
                            StateParkDescription = "test",
                            StateParkName = "Goose Lake",
                            YearRound = false
                        },
                        new
                        {
                            StateParkId = 2,
                            State = "Oregon",
                            StateParkDescription = "test",
                            StateParkName = "Smith Rock",
                            YearRound = false
                        },
                        new
                        {
                            StateParkId = 3,
                            State = "Oregon",
                            StateParkDescription = "test",
                            StateParkName = "The Cove Palisades",
                            YearRound = true
                        },
                        new
                        {
                            StateParkId = 4,
                            State = "Oregon",
                            StateParkDescription = "test",
                            StateParkName = "Cape Lookout",
                            YearRound = true
                        },
                        new
                        {
                            StateParkId = 5,
                            State = "Oregon",
                            StateParkDescription = "test",
                            StateParkName = "Oswald West",
                            YearRound = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
